config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
    @searched = params[:query] && params[:query] != ''
    @flats = Flat.where("name LIKE '%#{params[:query]}%'") if @searched
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flats_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
  <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.input :picture_url %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit flat</h1>
  <%= render 'form' %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All our Flats</h1>
  <% if @searched %>
    <p>You searched fo <strong><%= params[:query]  %></strong>. We found <%= @flats.size %> flats out of our <%= Flat.all.size %> on our website.</p>
  <% else %>
    <p>All <%= @flats.size %> flats</p>
  <% end %>
  <div class="cards-grid">
    <% @flats.each do |flat| %>
      <div class="card" style="width: 24rem;">
        <div class="card-body">
          <img src=<%= flat.picture_url %> class="card-img-top" alt="">
          <h4 class="card-title fw-bold"><%= flat.name %></h4>
          <p class="card-text"><%= flat.address %></p>
          <div>
            <i class="fa-solid fa-people-group"></i>
            <%= flat.number_of_guests %>
            <i class="fa-solid fa-euro-sign ms-3"></i>
            <%= flat.price_per_night %>
          </div>
          <hr>
          <div class='d-flex justify-content-around'>
            <%= link_to 'More info', flat_path(flat), class: 'text-primary' %>
            <%= link_to 'Edit', edit_flat_path(flat), class: 'text-warning' %>
            <%= link_to 'Remove', flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'text-danger' %>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>New flat</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url(<%= @flat.picture_url %>)"></div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <%= link_to 'Edit', edit_flat_path(@flat) %>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-text" id="start-date-label">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="start-date" aria-describedby="start-date-label">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-text" id="end-date-label">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="end-date" aria-describedby="start-date-label">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div>
          <div>
            <%= @flat.number_of_guests %> peoples
          </div>
          <div>
            <%= @flat.price_per_night %> €
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="d-flex justify-content-between">
          <h6 class="no-mb">Share</h6>
          <div>
            <i class="fa-brands fa-facebook-square me-2"></i>
            <i class="fa-brands fa-twitter-square me-2"></i>
            <i class="fa-brands fa-pinterest-square me-2"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
    <nav class='navbar navbar-expand-lg bg-light mb-3'>
      <div class="container-fluid">
         <%= link_to 'Simple Airbnb', flats_path, class: 'navbar-brand text-decoration-none' %>
         <div class="d-flex">

            <%= form_with url: "/", method: :get, class: 'd-flex me-2' do |form| %>
              <%= form.text_field :query, class: 'form-control me-2', placeholder: 'Search' %>
              <%= form.submit "Search", class: 'btn btn-outline-success' %>
            <% end %>


            <%# <form class="d-flex me-2" action='/search' role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> %>

            <button class="btn btn-outline-primary" type="submit">
              <%= link_to 'Add Flat', new_flat_path, class: 'text-decoration-none' %>
            </button>
         </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render '/layouts/navbar' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>